sling:
    # This image must be built first, from the
    # "slingbuild" folder 
    image: sling-nosql-demo:latest
    container_name: sling
    ports:
        - "8080:8080"
#    volumes:
#        - src/main/resources:/srv/images
#        - docker/sling:/opt/sling/sling

mongo:
    image: mongo:3.0
    container_name: mongo
    ports: 
        - "27017:27017"

couchbase:
    image: couchbase:community-4.0.0
    container_name: couchbase
    ports:
        - "8091:8091"
        - "8092:8092"
        - "8093:8093" # query port
        - "11210:11210"

redis:
    image: redis
    container_name: redis
    ports:
        - "6379:6379"